name: e_commerce
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sqflite: ^2.0.0+3
  fluttertoast: ^8.0.6
  image_cropper: ^1.4.0
  flutter_image: ^3.0.0
  image_picker: ^0.7.4
  path: ^1.8.0
  google_sign_in: ^5.0.1
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.5
  firebase_auth: ^1.0.1
  flutter_facebook_login: ^3.0.0
  get: ^4.1.2
  shared_preferences: ^2.0.5
  cloud_firestore: ^1.0.2
  provider: ^5.0.0
  flutter_svg_provider: ^0.1.8

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4


flutter_native_splash:
    color: "#ffffff"
    image: assets/images/Content.png
    android: true
    ios: true
    web: true
    android_gravity: fill
    ios_content_mode: scaleAspectFill

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/profileIcons/


  fonts:
    - family: sans
      fonts:
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-Regular.ttf
